clangd/vscode-clangd

package.json, src/extension.ts
Clangd still doesn't listen to these events, and these days it can
dynamically register file watchers if it wants to start.
=> Remove "sync file events" option.

.clang-format, src/extension.ts, src/semantic-highlighting.ts, test/index.ts, test/semantic-highlighting.test.ts
I refuse to believe `{ key : value }` is actually intended, I think just nobody really uses LLVM style for JS.
See also http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20140127/098286.html
=> Fix clang-format style

src/config.ts, src/extension.ts, src/install.ts, src/semantic-highlighting.ts, tsconfig.json
VSCode doesn't currently provide any APIs for extensions to expand these.
So we pick a few that seem useful and are easy to substitute.
Fixes https://github.com/clangd/vscode-clangd/issues/22
=> Support a subset of substitutions like ${workspaceRoot} in config.

src/install.ts
This doesn't make a lot of sense, but seems to be backwards-compat behavior.
Fixes #22
=> Interpret clangd.path relative to ${cwd} if it has a slash

src/semantic-highlighting.ts
The highlighting config is not from clangd, it is from vscode builtin workbench.
Fixes https://github.com/clangd/vscode-clangd/issues/27
=> Fix the wrong read config for highlighting.

package.json, src/extension.ts
Similar to YCM's "RestartServer" command.
If clangd crashes, vscode will try to restart clangd up to 5 times. After that, there is no way to restart clangd except reloading the vscode window. However, reloading the vscode window will lose the whole working context in vscode, especially you are running programs in the integrated terminal.
"clangd.restart" command will restart clangd server **without** reloading the vscode window.
=> Add "clangd.restart" command.

src/extension.ts
Fixes #31 
Tested on LLVM project, verified with qualified names and unqualified names.
=> Make workspaceSymbols work on qualified name.

package.json
When overridden, this tends to be machine-specific, especially when the
path is produced by autoinstall.
This change of scope should cause vscode to update the remote settings
rather than the (cross-machine) user ones, in the autoinstall flow.
=> Mark clangd.path as scope=machine

package-lock.json, package.json, src/extension.ts, src/file-status.ts, src/semantic-highlighting.ts, src/switch-source-header.ts, src/type-hierarchy.ts
For the record, this seems to be enough to enable support for the new semantic highlighting.
More of an RFC. It needs to be checked what [changed between LSP client 6.1.3 and the final version](https://github.com/microsoft/vscode-languageserver-node/commits/master/protocol/src/common/protocol.semanticTokens.proposed.ts) and which state will be included in the clangd-11 release (v10 falls back to the old implementation).
Even works in non-insiders vscode @sam-mccall.
It's also unclear if
```diff
-        "vscode": "^1.41.0"
+        "vscode": "^1.44.0"
-        "@types/vscode": "1.41.*",
+        "@types/vscode": "1.44.*",
```
offers anything due to https://code.visualstudio.com/updates/v1_44#_semantic-tokens-provider-api
=> support proposed official semantic highlighting API

package.json
This allows the setting to continue to be overridable per-workspace.
Fixes https://github.com/clangd/vscode-clangd/issues/64
=> Use scope=machine-overridable for clangd.path

src/clangd-context.ts, src/config-file-watcher.ts, src/extension.ts, src/file-status.ts, src/install.ts, src/semantic-highlighting.ts, src/switch-source-header.ts, src/type-hierarchy.ts
When restarting the clangd server, don't just call stop and activate on the same client, but instead tear down the client and instantiate a whole new one. This way we get to see any changed settings (e.g. `clangd.path` or `clangd.arguments`).
I'm new to VS Code development and to Typescript, so please be gentle if I'm doing something stupid here!
Addresses #77.
=> Re-read config when restarting server

src/memory-usage.ts
=> Save the Disposable returned when registering clangd.memoryUsage

package-lock.json, package.json
The newer versions are needed to support the call hierarchy protocol.
=> Bump vscode-languageclient and vscode-languageserver-types dependencies

package.json
The "show memory usage" button did not have a when clause, making it
show up in every view title across the editor.
=> Restrict memory usage button to its own view

.github/workflows/auto-release.yml, .github/workflows/ci.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Remove the deprecated set-env command.

src/config-file-watcher.ts
This prevents an error that occurs when the extension tries to register the watcher, but no folder is open (for example when only a single c file is).
With this fix, in this case no watcher is registered.
=> Prevent file watcher error when no folder is open

package.json, src/extension.ts, src/type-hierarchy.ts
Log in output is named "clangd" (was "Clangd Language Server")
Commands shown in palette are consistently "clangd: foo bar" (some were "foo clangd bar")
Exception: type hierarchy (proposed as standard LSP feature)
Internal resource IDs consistently clangd.foo (some were extension.vscode-clangd.foo)
=> Naming cleanups

src/config-file-watcher.ts
Restarting the server when this file changes doesn't make that much sense.
There can be .clang-tidy files in sub directories(and parent directories) that wont be watched so having the server restart when only the base directory configuration changes leads to non deterministic behaviour.
Ensuring clang-tidy configurations are up to date should be done on the clangd server instead. This could be done in a similar way to how the config files are cached but validated against modification time when accessed.
Going this route will also work for other editors that use clangd.
=> Remove the file watch on .clang-tidy

package-lock.json, package.json, src/clangd-context.ts, src/memory-usage.ts, src/semantic-highlighting.ts, src/switch-source-header.ts, src/type-hierarchy.ts
LSP 3.16.0 is officially released, and bump all dependencies.
Fix #58.
=> Bump vscode-languageclient and vscode-languageserver-types.

package.json, src/config-file-watcher.ts
Corresponds to https://reviews.llvm.org/D94222
This is the minimal change. I have a feeling the dispose/re-watch logic could be made cleaner.
But this client-side feature can just be removed in future, so I'm not sure it's worth the risk of trying to polish it.
I've tested this locally with clangd with/without the capability.
=> Disable config file watcher if a hot-reload capability is set

src/clangd-context.ts
Fixes https://github.com/clangd/vscode-clangd/issues/81
=> Tweak workspaceSymbols middleware to avoid suboptimal ordering of results

package.json, src/ast.ts, src/clangd-context.ts
See https://github.com/llvm/llvm-project/commit/8adc4d1ec76471bc283d888f3077f7d8f591d6ad
This extension is new, so the feature doesn't work with clangd 11 and earlier.
Implementation is pretty similar to memoryusage (though a bit simpler I think)
=> Add "show AST" command, based on textDocument/ast extension.

package.json, src/clangd-context.ts
Allowing us to control the maximum clangd restart times (by default it is 4), this would make the life of tracking/reporting crashes a bit easier.
=> Add a restartAfterCrash option

src/extension.ts
`vscode-clangd` is known to create confusing user experience when `ms-vscode.cpptools` extension is enabled but it is not clear to the users. This patch creates a warning for described scenario.
=> Warn about conflict with ms-vscode.cpptools

src/clangd-context.ts
If the rootPath of a project is a symlink vscode can execute clangd in
the users home-directory. This can cause problems if one is, for
example, using a wrapper script which relies on knowing the current
project. This solves this issue by forcing the clangd to execute in
`vscode.workspace.rootPath` if available.
Test: manual
=> Ensure clangd is executed in vscode.workspace.rootPath

package.json, src/clangd-context.ts, src/extension.ts, src/open-config.ts
Global config opening will likely not work on remote setups and is as of yet untested on windows and mac builds.
Fixes #176
=> Add commands to open global and project config

src/ast.ts, src/clangd-context.ts, src/config-file-watcher.ts, src/config.ts, src/file-status.ts, src/install.ts, src/memory-usage.ts, src/open-config.ts, src/semantic-highlighting.ts, src/switch-source-header.ts, src/type-hierarchy.ts, tsconfig.json
Closes #61.
Changes have been made to adhere to strict type checking:
- Non-null assertions and definite-assignment assertions (`!` post-fix operator) have been added to please the compiler (these do not affect the compiled output). These assertions are not always strictly "safe", but are not any less safe than not having strict type checking at all. Plus, their presence in the code can be a signal that maybe the design should be changed to safely ensure that the types are not null/undefined.
- Some optional chaining (`?.`) has been been added when properties can be null/undefined.
- Some incorrect uses of `null` have been replaced with `undefined`.
- Add `defaultValue` arguments to `WorkspaceConfiguration.get()` so that it will not return undefined. The default values being passed are …
=> Enable "strict" compiler option

package.json, src/extension.ts
I've added an option to control suppression of the incompatibility warning (and not change the C/C++ settings).
I'm making this pull request as suggested in https://github.com/clangd/vscode-clangd/issues/162, since others seem to have faced this same issue.
=> Add option to suppress warning about the Microsoft C/C++ extension incompatibility

package.json
Fixes #244.
Note that this displays "clangd: switch between source/header" in the context menu. The "clangd" prefix doesn't look good, but I can't seem to fix that without changing the title of the command (which also affects what one sees in the command palette). I'm not sure what's the best option.
=> Add switch header/source to editor context menu

package.json
Based on `activationEvents` in package.json, the plugin is only enabled for c/cpp/cuda/objc/obcpp, and all of those have header/source files (except maybe cuda?). I've confirmed with an objc .m/.h pair that this works correctly.
I also added a category for all commands and removed the clangd prefix from the title. This keeps the "clangd: " prefix on all commands in the command palette, but uses only the title in the context menu (which looks nicer).
=> enable switchheadersource for all langs, and add category to all commands

package-lock.json, package.json, src/clangd-context.ts
Bulitin cuda language was added in https://github.com/microsoft/vscode/commit/95420b39f28dab93e0764d442e74a7984a78ab38
=> Move to vscode builtin cuda-cpp language

src/inlay-hints.ts
Previous behavior: hints are only retained for visible tabs. Therefore
every time you switch tabs we need to request hints from the server
before they can be shown, even if the document hasn't changed.
New behavior: hints are obtained when a file is made visible and cached
until the file is *closed*. Switching tabs no longer issues inlayHints
requests (apart from the first time a tab is seen).
The cache-state handling is centralized around the update() function,
which will be helpful as we change it.
=> Inlay hints: retain hints for open files, not just visible ones.

src/inlay-hints.ts
Otherwise it is not released -- we hit a "command 'clangd.inlayHints.toggle' already exists" error
when we run the "restart clangd" command.
=> Subscribe the registered inlyHints.toggle command.

.vscodeignore, package-lock.json, package.json
This reduces vsix size from 1.5MB -> 500KB, and activate time by 60ms or so.
Note that esbuild consumes TS directly rather than running tsc, and
doesn't produce diagnostics. However they still show up in the editor,
and `test` will still fail on tsc compile errors.
=> Bundle the extension into one js file with esbuild.

.vscode/tasks.json, package.json
The `F5`-debugging workflow has been broken since #287, this patch brings it back.
=> Fix the broken debugging workflow.

package-lock.json, package.json, src/ast.ts, src/clangd-context.ts, src/config-file-watcher.ts, src/inlay-hints.ts, src/memory-usage.ts, src/type-hierarchy.ts
when using a standard-inlay-hint-supported clangd
- Fixes #342
- Also fixes the `clangd.inlayHints.toggle command not found` issue
=> Fix inlay-hint not shown issue 

src/clangd-context.ts
The use of commit-characters in clangd had good intentions, but it has
terrible UX in practice in VSCode, as documented on the linked bug.
We didn't notice this until it was far too late: the commit characters
were added in clangd 12, but bugs in vscode-languageclient prevented
them from being noticed until languageclient-8.
(https://github.com/microsoft/vscode-languageserver-node/issues/673)
At this point we can't go back and change the server behavior so we need
to override it on the client.
Fixes https://github.com/clangd/vscode-clangd/issues/357
=> Disable commit-characters for all code completion.

.vscode/tasks.json, DEVELOPING.md, package.json
A bunch of stuff in the docs is out of date.
Also we no longer have any recommended workflows that use --watch.
=> Update developer docs, don't --watch by default

src/extension.ts
The casing for `C_Cpp.intelliSenseEngine` was recently changed in microsoft/vscode-cpptools#9862 to be lowercase, but this extension will complain every 5 seconds unless the configuration value is strictly the capitalized "Disabled". This uses `toLowerCase()` to still support the legacy capitalized value just like the cpptools extension.
=> Fix cpptools disabled check to be case-insensitive

src/type-hierarchy.ts
Due to a conflict in advertising capability for clangd's type-hierarchy
extension and standard protocol we're going to have both of them available
in newer vscode clients (while clangd's prior to 15 release won't be able to
provide support for the standard protocol).
This patch ensures we're only showing one version of type-hierarchy, preferring
the standard one when clangd supports it, and disabling the standard when clangd
doesn't have support.
=> [TypeHierarchy] Properly handle standard protocol

src/ast.ts, src/type-hierarchy.ts
In the type hierarchy tree and AST tree code, both `vscode.window.registerTreeDataProvider` and `vscode.window.createTreeView` are called with the same ID, `clangd.typeHierarchyView` and `clangd.ast`, respectively. These calls are redundant, as `registerTreeDataProvider` just delegates to `createTreeView`:
https://github.com/microsoft/vscode/blob/6f7820c454195fd9d9749022f911a08a004f34bd/src/vs/workbench/api/common/extHostTreeViews.ts#L81-L84
VSCode handles the redundancy gracefully, but when the plugin is run in Theia, errors are logged about both views:
=> Remove redundant `TreeDataProvider` registrations

package.json, src/clangd-context.ts, src/config.ts, src/extension.ts, src/install.ts
See discussion in:
- https://github.com/clangd/vscode-clangd/issues/318
- https://github.com/clangd/clangd/discussions/1488
This PR removes the custom logic and sets the configuration items `clangd.path` and `clangd.arguments` to limited in restricted mode.
=> Remove custom secure configuration items and rely on workspace trust from vscode

src/clangd-context.ts
this.client may not have been set if activate() failed for some reason (e.g. the clangd executable could not be found and the user opted not to install it via auto-install)
Partially fixes https://github.com/clangd/vscode-clangd/issues/406
=> Avoid undefined object access in ClangdContext.dispose()

CHANGELOG.md, package.json, src/clangd-context.ts, src/inactive-regions.ts
This patch intercepts the semantic tokens requests using middleware,
extracts the inactive code ranges, and uses setDecorations() to
provide whole-line background highlighting for them.
=> Improve presentation of inactive region highlight

src/config.ts
Resolves #485 
Noticed my silly mistake
=> Added handling of predefined variable ${userHome}

package.json
Just found "Show AST" menu will be shown in unrelated places like vscode output channel or even json file after clangd activated.
This patch restricts 'Show AST' menu to supported files only.
=> Restrict 'Show AST' menu to supported files only

package.json
At the moment, the `Close` commands for each contributed view:
- All have the same title `"Close"`
- Are all enabled and visible in the command palette even if the corresponding view isn't actually visible
This PR
- Adds details about the view to be closed to the title so that each is distinct
- Uses a `${viewId}.visible` context key that is [automatically set up by VSCode](https://github.com/microsoft/vscode/blob/bccfade64adb249f57c8fcf03cba41609f76ce5c/src/vs/workbench/services/views/browser/viewDescriptorService.ts#L892) for each view to determine enablement.
=> Label "close" commands for views; improve enablement

src/clangd-context.ts
As recommended in https://github.com/microsoft/vscode/issues/78806 This is an incomplete fix but better than nothing. Also files https://github.com/microsoft/vscode/issues/164310 in case VSCode can improve the behavior here.
fixes https://github.com/clangd/vscode-clangd/issues/390
=> Trigger signature help when accepting code completions, where appropriate

src/clangd-context.ts, src/extension.ts, test/inactive-regions.test.ts
Fixes https://github.com/clangd/vscode-clangd/issues/502
=> Gracefully handle 'clangd.restart' being invoked when the extension hasn't been activated yet

package.json, src/clangd-context.ts
Fixes https://github.com/clangd/vscode-clangd/issues/588
=> Add an option to disable code completion

src/clangd-context.ts, src/extension.ts, test/inactive-regions.test.ts
The intention was to only catch the case where the language server is already starting because running the restart command triggered activation of the plugin, but it was also catching the case where the language server wasn't running at all.
Fixes https://github.com/clangd/vscode-clangd/issues/599
=> Fix check for clangd.restart being a no-op

src/inactive-regions.ts
This PR fixes issue #600, by calling `dispose` for the `decorationType` member of `InactiveRegionsFeature` objects during their own disposal.  Doing so removes the applied decorations, preventing them from persisting after the the extension is stopped or restarted.
=> Clear All Decorations in `dispose`

src/inactive-regions.ts
At present, when changing the 'inactive-regions' settings, users need to restart VSCode for the changes to take effect. This PR makes the extension automatically applies these effects upon detecting user modifications to the settings, enhancing user experience.
=> Update decoration type for inactive-regions when settings change

src/config.ts
It's useful in my scenario when I'm creating a build dir that name depends on the name of workspace
=> Add handling of predefined variable ${workspaceFolderBasename}

api/README.md, api/package.json, api/vscode-clangd.d.ts, src/api.ts, src/ast.ts, src/extension.ts
This PR exports the language client so other VS Code extensions can take advantage of the clangd LSP features.
For example, domain specific functionality (e.g. intrinsics) could be implemented in a separate extension and trivially leverage the full-featured AST functionality exposed by clangd.
This has been tested and working with a trivial hover example:
```typescript
import * as vscode from 'vscode';
import { BaseLanguageClient, Range, TextDocumentIdentifier, RequestType } from 'vscode-languageclient';
import { ClangdExtension } from ''
const CLANGD_EXTENSION = 'llvm-vs-code-extensions.vscode-clangd';
const CLANGD_API_VERSION = 1;
interface ClangdApiV1 {
languageClient: BaseLanguageClient
}
interface ClangdExtension {
getApi(version: 1): ClangdApiV1;
}
interface ASTParams { …
```
=> Export client from activation as API for use in other extensions

src/api.ts, src/extension.ts
Fix for #648
This PR update language client in exported API, after clangd restarting.
=> Update language client in exported API, on `clangd.restart`

package.json
The clangd extension does not restrict the default keybindings for the `clangd.switchheadersource` and `clangd.typeHierarchy` commands to supported language ids. This has the effect of blocking other extensions from using these shortcuts for actions. Using the same shortcut for providing similar functionality for familiarity can be desirable for other extensions.
This PR adds a check for the supported language ids to the `when` clauses.
=> Restrict keybindings to supported files

package.json, src/clangd-context.ts
Fixes https://github.com/clangd/vscode-clangd/issues/692
=> Add an option to disable hovers

src/clangd-context.ts
In VsCode 1.72 Node was updated to version 20, before this upgrade, it was possible to execute cmd/bat scripts as executable.
After this update this was suddenly broken.
Our use-case for using such a script has to do with the consistency of our clang-tooling.
We build clang-format, clang-tidy, clangd ... all together and put this in a package manager.
In the script, we first download these executables (when needed) and than start the downloaded clangd.
As such, when fixing an issue in clang-tidy, the same issue will get fixed in the clangd exe.
Without this script, it is impossible to automatically trigger this download and it introduces the risk that we do not update all the tooling to the latest version.
=> fix #683 Restore VsCode 1.91 behavior of allowing scripts as executable

src/clangd-context.ts
The last change `0c2d40d7d6b8092309bd2c880a32e59c71472a80` add `shell: true` to clangd options, which cause the extension activate failed if there is a space in clangd's path.
Especially on windows, clangd installed under 'C:\Program Files\'
=> FIX: extension activate failed if there is a space in clangd path

package.json, src/extension.ts
I know that this could be done by disabling the extension for a given workspace, but that requires everyone working in the repository to do that via the VS Code GUI. This allows the extension to be disabled in the workspace settings which can be committed to the repo.
In our organization we're looking to transition from using `cpptools` to `clangd` and having an easy way to have both extensions installed but only one enabled in a given workspace will be extremely helpful for us. We can already have a workspace that has been migrated to `clangd` disable Intellisense via `cpptools`, but there's no equivalent on the `clangd` side that I was able to find. For workspaces that haven't been migrated, `clangd` and `cpptools` will conflict until the `clangd` extension is disabled manually.
=> Add option to enable/disable clangd

api/README.md, api/vscode-clangd.d.ts, src/api.ts, src/clangd-context.ts, src/extension.ts, src/install.ts
Fixes https://github.com/clangd/vscode-clangd/issues/721
=> Support API usage when clangd is disabled or failed to initialize properly

DEVELOPING.md, package.json, src/clangd-context.ts
In VsCode 1.72 Node was updated to version 20, before this upgrade, it was possible to execute cmd/bat scripts as executable.After this update this was suddenly broken.
Our use-case for using such a script has to do with the consistency of our clang-tooling.
We build clang-format, clang-tidy, clangd ... all together and put this in a package manager.
In the script, we first download these executables (when needed) and than start the downloaded clangd.
As such, when fixing an issue in clang-tidy, the same issue will get fixed in the clangd exe.
Without this script, it is impossible to automatically trigger this download and it introduces the risk that we do not update all the tooling to the latest version.
Fixes clangd#683
In this reapply, we quote both the command line and the arguments, …
=> Restore VsCode 1.91 behavior of allowing scripts as executable

src/clangd-context.ts
- The disposables passed in to install.activate() were not saved for cleanup
- config.get() is not async
=> Follow-up cleanups after #728

CHANGELOG.md, DEVELOPING.md, package-lock.json, package.json, src/clangd-context.ts
This reverts commit ea588aa77d6eb0f75a9592d90ea68aeb9b50fbba.
Fixes https://github.com/clangd/vscode-clangd/issues/734
=> Revert #730 and release 0.1.33

src/clangd-context.ts
Other minor cleanup:
- do not await config.get(), it's not async
- move initialization of clangdArguments into create()
Fixes https://github.com/clangd/vscode-clangd/issues/739
=> Clean up disposables in early-return path of ClangdContext.create()

.github/workflows/unstable-release.yml
The workflow is manually triggered, and creates a Github release containing a build from the master branch.
=> Add a Github workflow for creating an unstable release

DEVELOPING.md, package.json, src/clangd-context.ts
After this update this was suddenly broken.
Our use-case for using such a script has to do with the consistency of our clang-tooling.
We build clang-format, clang-tidy, clangd ... all together and put this in a package manager.
In the script, we first download these executables (when needed) and than start the downloaded clangd.
As such, when fixing an issue in clang-tidy, the same issue will get fixed in the clangd exe.
Without this script, it is impossible to automatically trigger this download and it introduces the risk that we do not update all the tooling to the latest version.
Fixes clangd#683
In this reapply, we quote both the command line and the arguments, such that both can contain spaces. We also introduce the option useScriptAsExecutable, such that this is only enabled when …
=> In VsCode 1.72 Node was updated to version 20, before this upgrade, it was possible to execute cmd/bat scripts as executable.

src/clangd-context.ts
There is some prior discussion in #31 that doesn't directly address this issue--it appears to me searching for a symbol with a leading `::` always fails: results from clangd strip the leading `::`, so vscode fuzzy match will filter out all results unless we add prefix back, which is easy enough to do.
=> Handle workspace symbols searches with a '::' prefix

package.json, src/clangd-context.ts, src/config-file-watcher.ts
This addresses this issue: https://github.com/clangd/vscode-clangd/issues/300
This is to take over this pull request: https://github.com/clangd/vscode-clangd/pull/688
Re-enable the functionality of file watcher since clangd's builtin restart functionality does not refresh opened files in vscode, leading to potentially misleading ifdef view.
I have addressed the comments on that PR.
=> [#300] Re-enable the functionality of file watcher

package.json
Per
https://llvm.org/docs/Security.html#what-is-considered-a-security-issue,
parsing untrusted code through clang can result in harmful behavior.
Also it isn't considered as a security-sensitive component, hence its on
embedders like vscode-clangd to ensure users are aware of such risks.
Hence this patch disables running clangd on untrusted workspaces.
=> Disable clangd on untrusted workspaces

package.json, src/config-file-watcher.ts
`onConfigChanged.forceEnable` doesn't work due to a naming conflict with `onConfigChanged`. If the latter is defined then the former can't be set.
This PR simply renames `onConfigChanged.forceEnable` to `onConfigChangedForceEnable`.
=> Fix onConfigChanged.forceEnable

.github/dependabot.yml
This dependency defines the minimum supported version of VSCode, so we
want this to be a manual thing.
=> dependabot: ignore updates to @types/vscode

src/install.ts
This change fixes error messages like `clangd {0} is now installed.` to include the interpolated string values (e.g. `clangd 20.1.0 is now installed.`).
`UI.localize` is a function that is [declared in `node-clangd`](https://github.com/clangd/node-clangd/blob/040ebbdcb135daf87053504ab4aaa13c1278de43/src/index.ts#L58-L69) that supports templating via substrings like `{0}` and `{1}`. `vscode-clangd` implements this templating with `String.prototype.replace`, which returns a new string rather than mutating the existing one.
=> Fix UI.localize function to use placeholders

src/clangd-context.ts, src/config-file-watcher.ts, src/config.ts, src/inactive-regions.ts, src/install.ts, test/inactive-regions.test.ts
Fix #48.
- Make `config.get` async, change all usage to support this.
- Add a new replacement for `command:` variables.
=> Support commands in config
